name: stale-issue

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mark-stale:
    uses: ./.github/workflows/_stale.yml
    permissions:
      issues: write
      pull-requests: write
    with:
      days-until-stale: 60
      days-until-close: 20
      stale-label: "stale"
      exempt-label: "keep"
